logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.150.101 # rabbitMQµÄipµØÖ·
    port: 5672 # ¶Ë¿Ú
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1